//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prodavnica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class narudzbenica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public narudzbenica()
        {
            this.narudzbenicaProizvod = new HashSet<narudzbenicaProizvod>();
        }
    
        public int idNarudzbenica { get; set; }
        public System.DateTime datumFormiranjaNar { get; set; }
        public System.DateTime datumIzmeneNar { get; set; }
        public string slanjeIme { get; set; }
        public string slanjePrezime { get; set; }
        public string slanjeAdresa { get; set; }
        public string slanjeGrad { get; set; }
        public string slanjeDrzava { get; set; }
        public string slanjeZIP { get; set; }
        public string placanjeIme { get; set; }
        public string placanjePrezime { get; set; }
        public string placanjeAdresa { get; set; }
        public string placanjeGrad { get; set; }
        public string placanjeDrzava { get; set; }
        public string placanjeZIP { get; set; }
        public double postarina { get; set; }
        public int idKorisnik { get; set; }
    
        public virtual korisnik korisnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<narudzbenicaProizvod> narudzbenicaProizvod { get; set; }
    }
}
