//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prodavnica.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class prodavnicaEntities : DbContext
    {
        public prodavnicaEntities()
            : base("name=prodavnicaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<kategorija> kategorija { get; set; }
        public virtual DbSet<korisnik> korisnik { get; set; }
        public virtual DbSet<narudzbenica> narudzbenica { get; set; }
        public virtual DbSet<narudzbenicaProizvod> narudzbenicaProizvod { get; set; }
        public virtual DbSet<proizvod> proizvod { get; set; }
        public virtual DbSet<slike> slike { get; set; }
    }
}
