//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prodavnica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proizvod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public proizvod()
        {
            this.narudzbenicaProizvod = new HashSet<narudzbenicaProizvod>();
            this.slike = new HashSet<slike>();
        }
    
        public int idProizvod { get; set; }
        public string nazivProizvod { get; set; }
        public string opisProizvod { get; set; }
        public string slikaProizvod { get; set; }
        public double cenaProizvod { get; set; }
        public Nullable<int> popustProizvod { get; set; }
        public int statusProizvod { get; set; }
        public System.DateTime datumUnosaProizvod { get; set; }
        public Nullable<System.DateTime> datumIzmeneProizvod { get; set; }
        public int idKategorija { get; set; }
    
        public virtual kategorija kategorija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<narudzbenicaProizvod> narudzbenicaProizvod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<slike> slike { get; set; }
    }
}
